// HomePage
export const FETCHING_RESTAURANT_LIST = 'FETCHING_RESTAURANT_LIST'
export const FETCHING_RESTAURANT_LIST_SUCCESS = 'FETCHING_RESTAURANT_LIST_SUCCESS'
export const FETCHING_RESTAURANT_LIST_FAILURE = 'FETCHING_RESTAURANT_LIST_FAILURE'
export const SEARCHING_RESTAURANT_SUCCESS = 'SEARCHING_RESTAURANT_SUCCESS'
export const SEARCHING_RESTAURANT_FAILURE = 'SEARCHING_RESTAURANT_FAILURE'
//Navigation
export const NAVIGATE_TO_RESTAURANT_DETAIL = 'NAVIGATE_TO_RESTAURANT_DETAIL'
//BookingForm
export const FILL_DATE = 'FILL_DATE'
export const FILL_TIME = 'FILL_TIME'
export const FILL_NUM_OF_CUSTOMER = 'FILL_NUM_OF_CUSTOMER'
export const FILL_PHONE_NUMBER = 'FILL_PHONE_NUMBER'
export const FILL_CUSTOMER_NAME = 'FILL_CUSTOMER_NAME'
export const PRESS_NEXT_AT_BOOKING = 'PRESS_NEXT_AT_BOOKING'
