// HomePage
export const FETCHING_RESTAURANT_LIST = 'FETCHING_RESTAURANT_LIST'
export const FETCHING_RESTAURANT_LIST_SUCCESS = 'FETCHING_RESTAURANT_LIST_SUCCESS'
export const FETCHING_RESTAURANT_LIST_FAILURE = 'FETCHING_RESTAURANT_LIST_FAILURE'
export const SEARCHING_RESTAURANT_SUCCESS = 'SEARCHING_RESTAURANT_SUCCESS'
export const NO_RESTAURANT_DATA = 'NO_RESTAURANT_DATA'
export const NO_MATCHED_RESTAURANT = 'NO_MATCHED_RESTAURANT'
//Navigation
export const NAVIGATE_TO_RESTAURANT_DETAIL = 'NAVIGATE_TO_RESTAURANT_DETAIL'
export const NAVIGATE_TO_BOOKING_DETAIL = 'NAVIGATE_TO_BOOKING_DETAIL'
//BookingForm
export const FILL_DATE = 'FILL_DATE'
export const FILL_TIME = 'FILL_TIME'
export const FILL_NUM_OF_CUSTOMER = 'FILL_NUM_OF_CUSTOMER'
export const FILL_PHONE_NUMBER = 'FILL_PHONE_NUMBER'
export const FILL_CUSTOMER_NAME = 'FILL_CUSTOMER_NAME'
export const PRESS_NEXT_AT_BOOKING = 'PRESS_NEXT_AT_BOOKING'
//EstimatedTimeTable
export const FETCHING_ESTIMATED_TIME_TABLE_SUCCESS = 'FETCHING_ESTIMATED_TIME_TABLE_SUCCESS'
//MyBooking
export const FETCHING_MY_BOOKING_LIST = 'FETCHING_MY_BOOKING_LIST'
export const FETCHING_MY_BOOKING_LIST_SUCCESS = 'FETCHING_MY_BOOKING_LIST_SUCCESS'
export const FETCHING_MY_BOOKING_LIST_FAILURE = 'FETCHING_MY_BOOKING_LIST_FAILURE'
export const NO_MY_BOOKING_DATA = 'NO_MY_BOOKING_DATA'
//EditMyBooking
export const PREPARE_EDITED_VALUE = 'PREPARE_EDITED_VALUE'
export const EDIT_NUM_OF_CUSTOMER = 'EDIT_NUM_OF_CUSTOMER'
export const EDIT_PHONE_NUMBER = 'EDIT_PHONE_NUMBER'
export const EDIT_CUSTOMER_NAME = 'EDIT_CUSTOMER_NAME'
