export const FETCHING_RESTAURANT_LIST = 'FETCHING_RESTAURANT_LIST'
export const FETCHING_RESTAURANT_LIST_SUCCESS = 'FETCHING_RESTAURANT_LIST_SUCCESS'
export const FETCHING_RESTAURANT_LIST_FAILURE = 'FETCHING_RESTAURANT_LIST_FAILURE'
